"""Catalog loading and validation.

Two halves, kept apart on purpose:

  catalog/services/*.yaml   closed AI services: how to recognise them in a codebase,
                            and which pools of open source alternatives replace them.
  catalog/alternatives.yaml the pools themselves.
  catalog/rankings.json     generated by scripts/refresh.py: every pool ranked by
                            momentum. Optional — without it, pools keep file order.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

import yaml

# OSI-approved licences, as GitHub reports them. A project outside this list is not
# offered as an open source alternative, however popular it is.
OPEN_LICENCES = frozenset(
    {
        "Apache-2.0",
        "MIT",
        "BSD-2-Clause",
        "BSD-3-Clause",
        "ISC",
        "MPL-2.0",
        "GPL-2.0",
        "GPL-3.0",
        "LGPL-2.1",
        "LGPL-3.0",
        "AGPL-3.0",
        "EPL-2.0",
        "BSL-1.0",
        "PostgreSQL",
        "Unlicense",
        "Zlib",
    }
)
# Model weights, as Hugging Face model cards spell them. Custom "open" licences with
# use restrictions (llama, gemma, openrail, *-nc) are deliberately absent.
OPEN_MODEL_LICENCES = frozenset(
    {"apache-2.0", "mit", "bsd-3-clause", "bsd-2-clause", "cc-by-4.0", "cc-by-sa-4.0", "mpl-2.0"}
)

DETECT_KINDS = frozenset(
    {
        # packages, per ecosystem
        "requirement", "npm", "go", "cargo", "maven", "nuget", "gem", "composer", "pub",
        "swift",
        # code and configuration
        "python_import", "symbol", "model", "endpoint", "env", "terraform_resource",
    }
)  # fmt: skip
POOL_SOURCES = frozenset({"github", "huggingface"})


class CatalogError(ValueError):
    """Raised when a catalog file does not meet the schema."""


@dataclass(frozen=True)
class Alternative:
    name: str
    url: str
    what: str
    licence: str | None = None
    # GitHub projects
    stars: int | None = None
    stars_90d: int | None = None
    # Hugging Face models
    downloads: int | None = None
    trending: int | None = None


@dataclass(frozen=True)
class Pool:
    id: str
    name: str
    source: str
    alternatives: tuple[Alternative, ...]
    # "momentum", "stars" or "trending"; None when no rankings snapshot covers the pool
    # and the alternatives are in catalog order.
    ranked_by: str | None


@dataclass(frozen=True)
class Service:
    id: str
    name: str
    category: str
    replace_with: tuple[str, ...]
    detect: dict[str, tuple[str, ...]]
    # Ids of more general services whose evidence this one claims in the files where
    # it is used: Azure OpenAI is called through the `openai` package.
    excludes: tuple[str, ...] = ()
    # Open-weight models that a `model` prefix would otherwise catch: `openai/gpt-`
    # must not report `openai/gpt-oss-120b`, which anyone can run.
    open_models: tuple[str, ...] = ()
    # Signature values that cannot establish the service alone, because something
    # unrelated shares them: `import fireworks` is also the FireWorks workflow library.
    # Grouped: two weak signatures corroborate each other only across groups, so
    # `mongodb.net` and `ATLAS_URI` (both just "Atlas") don't make vector search.
    weak_groups: tuple[tuple[str, ...], ...] = ()

    @property
    def weak(self) -> tuple[str, ...]:
        return tuple(v for group in self.weak_groups for v in group)

    # The SDK doubles as the client for self-hosted OpenAI-compatible servers, so
    # evidence next to a local base URL (Ollama, vLLM, LM Studio) does not count.
    local_compatible: bool = False
    # A capability of a broader service (OpenAI Embeddings is part of the OpenAI API).
    # Its model ids count as real evidence when the broader service is itself in use.
    part_of: tuple[str, ...] = ()


@dataclass
class Catalog:
    services: list[Service] = field(default_factory=list)
    pools: dict[str, Pool] = field(default_factory=dict)
    rankings_date: str | None = None

    def __len__(self) -> int:
        return len(self.services)

    def by_id(self, service_id: str) -> Service | None:
        return next((s for s in self.services if s.id == service_id), None)

    def alternatives_for(self, service: Service) -> list[Pool]:
        return [self.pools[p] for p in service.replace_with]

    @property
    def categories(self) -> list[str]:
        return sorted({s.category for s in self.services})


def _as_tuple(value) -> tuple[str, ...]:
    if value is None:
        return ()
    if isinstance(value, str):
        return (value,)
    return tuple(str(v) for v in value)


def _load_pools(path: Path, rankings: dict) -> dict[str, Pool]:
    raw = yaml.safe_load(path.read_text("utf-8")) or {}
    pools: dict[str, Pool] = {}
    for item in raw.get("pools") or []:
        pool_id = item.get("id")
        for key in ("id", "name", "source"):
            if not item.get(key):
                raise CatalogError(f"{path.name}: pool '{pool_id}' is missing '{key}'")
        if item["source"] not in POOL_SOURCES:
            raise CatalogError(
                f"{path.name}: pool '{pool_id}' has unknown source '{item['source']}'"
            )
        if pool_id in pools:
            raise CatalogError(f"{path.name}: duplicate pool id '{pool_id}'")

        if item["source"] == "github":
            projects = item.get("projects") or []
            if not projects:
                raise CatalogError(f"{path.name}: pool '{pool_id}' lists no projects")
            repos = [p.get("repo", "") for p in projects]
            for p in projects:
                if not p.get("repo") or p["repo"].count("/") != 1 or not p.get("what"):
                    raise CatalogError(
                        f"{path.name}: pool '{pool_id}' has a project without "
                        "'owner/repo' and 'what'"
                    )
                if p.get("licence") and p["licence"] not in OPEN_LICENCES:
                    raise CatalogError(
                        f"{path.name}: {p['repo']} declares licence '{p['licence']}', "
                        f"which is not in the open source allowlist"
                    )
            if len(set(repos)) != len(repos):
                raise CatalogError(f"{path.name}: pool '{pool_id}' lists a repo twice")
        elif not item.get("pipeline_tags") or not item.get("publishers"):
            raise CatalogError(
                f"{path.name}: huggingface pool '{pool_id}' needs 'pipeline_tags' and 'publishers'"
            )

        snapshot = (rankings.get("pools") or {}).get(pool_id)
        if snapshot:
            alts = tuple(_from_snapshot(e, item["source"]) for e in snapshot["ranked"])
            ranked_by = snapshot.get("ranked_by", "stars")
        else:
            alts = tuple(
                Alternative(
                    name=p["repo"],
                    url=f"https://github.com/{p['repo']}",
                    what=p["what"],
                    licence=p.get("licence"),
                )
                for p in item.get("projects") or []
            )
            ranked_by = None
        pools[pool_id] = Pool(
            id=pool_id,
            name=item["name"],
            source=item["source"],
            alternatives=alts,
            ranked_by=ranked_by,
        )
    return pools


def _from_snapshot(entry: dict, source: str) -> Alternative:
    if source == "github":
        return Alternative(
            name=entry["repo"],
            url=entry["url"],
            what=entry.get("what", ""),
            licence=entry.get("licence"),
            stars=entry.get("stars"),
            stars_90d=entry.get("stars_90d"),
        )
    return Alternative(
        name=entry["id"],
        url=entry["url"],
        what=f"{entry.get('pipeline_tag', 'model')} model, released {entry.get('created', '?')}",
        licence=entry.get("licence"),
        downloads=entry.get("downloads"),
        trending=entry.get("trending"),
    )


def _parse_service(raw: dict, where: Path, pools: dict[str, Pool]) -> Service:
    service_id = str(raw.get("id", "<no id>"))
    for key in ("id", "name", "category", "replace_with", "detect"):
        if not raw.get(key):
            raise CatalogError(f"{where.name}: service '{service_id}' is missing '{key}'")

    detect: dict[str, tuple[str, ...]] = {}
    for kind, values in (raw["detect"] or {}).items():
        if kind not in DETECT_KINDS:
            raise CatalogError(
                f"{where.name}: service '{service_id}' uses unknown detect kind '{kind}'"
            )
        detect[kind] = _as_tuple(values)
    if not any(detect.values()):
        raise CatalogError(f"{where.name}: service '{service_id}' has no detection signatures")

    replace_with = _as_tuple(raw["replace_with"])
    for pool_id in replace_with:
        if pool_id not in pools:
            raise CatalogError(
                f"{where.name}: service '{service_id}' names pool '{pool_id}', "
                f"which is not in alternatives.yaml"
            )
    signatures = {v for values in detect.values() for v in values}
    # `weak: [a, b]` is two groups of one; `weak: [[a, b], c]` makes a and b one group.
    weak_groups = tuple(
        _as_tuple(item) if isinstance(item, list) else (str(item),)
        for item in raw.get("weak") or []
    )
    for group in weak_groups:
        for value in group:
            if value not in signatures:
                raise CatalogError(
                    f"{where.name}: service '{service_id}' marks '{value}' weak, "
                    f"but it is not one of its signatures"
                )
    return Service(
        id=service_id,
        name=str(raw["name"]),
        category=str(raw["category"]),
        replace_with=replace_with,
        detect=detect,
        excludes=_as_tuple(raw.get("excludes")),
        open_models=_as_tuple(raw.get("open_models")),
        weak_groups=weak_groups,
        local_compatible=bool(raw.get("local_compatible", False)),
        part_of=_as_tuple(raw.get("part_of")),
    )


def load_catalog(path: Path) -> Catalog:
    """Load a catalog directory: services/*.yaml, alternatives.yaml, rankings.json."""
    services_dir = path / "services"
    files = sorted(services_dir.glob("*.yaml")) if services_dir.is_dir() else []
    if not files:
        raise CatalogError(f"no service files found in {services_dir}")

    rankings_file = path / "rankings.json"
    rankings = json.loads(rankings_file.read_text("utf-8")) if rankings_file.is_file() else {}
    pools = _load_pools(path / "alternatives.yaml", rankings)

    catalog = Catalog(pools=pools, rankings_date=rankings.get("generated"))
    seen: dict[str, Path] = {}
    for file in files:
        raw = yaml.safe_load(file.read_text(encoding="utf-8")) or []
        if not isinstance(raw, list):
            raise CatalogError(f"{file.name}: expected a list of services")
        for item in raw:
            if not isinstance(item, dict):
                raise CatalogError(f"{file.name}: expected a service, found {type(item).__name__}")
            service = _parse_service(item, file, pools)
            if service.id in seen:
                raise CatalogError(
                    f"duplicate service id '{service.id}' in {file.name} "
                    f"and {seen[service.id].name}"
                )
            seen[service.id] = file
            catalog.services.append(service)

    for service in catalog.services:
        for other in (*service.excludes, *service.part_of):
            if other not in seen:
                raise CatalogError(f"service '{service.id}' names unknown service '{other}'")
    return catalog
