#!/usr/bin/env python3
"""List the API hosts and credential-like settings a codebase names, for a quick
comparison with what unrent reported. Standard library only.

    python sweep.py <repo> [--known scan.json] [--all]

unrent only detects services in its catalog. A host or key in this list that no unrent
finding explains is a candidate for a closed service it does not know. Documentation,
lockfiles, vendored code, and well-known non-AI hosts are skipped. With --known (the
JSON of `unrent scan --format json`), hosts and keys that already appear in unrent's
evidence are left out.

To keep the list short enough to read: a generated file (a models.dev catalog, an
OpenAPI client) gets one summary line, names seen only in tests are listed on one line,
and *_KEY / *_URL names that are never read from the environment or set in config are
dropped as code constants.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

SKIP_DIRS = {
    ".git", "node_modules", "vendor", "third_party", "dist", "build", ".venv", "venv",
    "__pycache__", ".next", "coverage", "site-packages", "locales", "i18n", "docs",
}  # fmt: skip
SKIP_SUFFIXES = {
    ".md", ".mdx", ".rst", ".txt", ".lock", ".svg", ".png", ".jpg", ".jpeg", ".gif",
    ".ico", ".pdf", ".map", ".min.js", ".css", ".scss", ".woff", ".woff2", ".ttf",
    ".zip", ".gz", ".csv", ".ipynb_checkpoints",
}  # fmt: skip
SKIP_NAMES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "uv.lock",
    "go.sum", "Cargo.lock", "CHANGELOG", "LICENSE",
}  # fmt: skip
# Hosts that are never an AI service a codebase depends on.
NOISE = re.compile(
    r"(^|\.)(github\.com|githubusercontent\.com|gitlab\.com|npmjs\.(com|org)|pypi\.org|"
    r"python\.org|w3\.org|schema\.org|example\.(com|org)|localhost|shields\.io|"
    r"googleapis\.com/css|fonts\.(googleapis|gstatic)\.com|jsdelivr\.net|unpkg\.com|"
    r"cloudflare\.com/cdnjs|mozilla\.org|wikipedia\.org|stackoverflow\.com|"
    r"docker\.(com|io)|apache\.org|opensource\.org|creativecommons\.org|"
    r"twitter\.com|x\.com|linkedin\.com|youtube\.com|discord\.(gg|com)|medium\.com|"
    r"readthedocs\.io|readthedocs\.org|json-schema\.org|mit-license\.org)$"
)
URL = re.compile(r"https?://([A-Za-z0-9][A-Za-z0-9.-]*\.[A-Za-z]{2,})(?::\d+)?(/[^\s\"'`)<>,]*)?")
SETTING = re.compile(
    r"\b([A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*_(?:API_KEY|APIKEY|KEY|TOKEN|SECRET|API_BASE|"
    r"BASE_URL|API_URL|ENDPOINT|HOST|URL))\b"
)
GENERIC_SETTINGS = re.compile(
    r"^(DATABASE_URL|REDIS_URL|POSTGRES_\w+|MYSQL_\w+|MONGO\w*|SECRET_KEY|JWT_\w+|"
    r"SESSION_\w+|AUTH_\w+|NEXTAUTH_\w+|GITHUB_TOKEN|NPM_TOKEN|PYPI_\w+|SENTRY_\w+|"
    r"AWS_SECRET_ACCESS_KEY|SMTP_\w+|MAIL_\w+|STRIPE_\w+|SLACK_\w+|CSRF_\w+|HOST|"
    r"\w*_PORT|BASE_URL|API_URL|PUBLIC_URL|APP_URL|SITE_URL|FRONTEND_URL|BACKEND_URL)$"
)
API_HINT = re.compile(r"(^api\.|\.ai$|inference|llm|model|search|embed|/v\d+\b|/api\b)", re.I)
TEST_PART = re.compile(
    r"(^|/)(tests?|specs?|__tests__|fixtures?|e2e|mocks?)(/|$)|[._]test\.|_spec\.|\.spec\.", re.I
)


CELL_TYPE = re.compile(r'"cell_type":\s*"(\w+)"')
NB_PART = re.compile(r'\s*"(source|outputs|metadata|attachments)":')
# A credential or endpoint setting is read from the environment or set in config. A name
# like TOOL_META_KEY that never is, is a constant in the code (a dict key), not a setting.
ENV_READ = re.compile(
    r"getenv|environ|process\.env|import\.meta\.env|ENV\[|System\.getenv|os\.Getenv|"
    r"_env\(|env\(|\$\{?[A-Z]|valueFrom|secretKeyRef"
)
CONFIG_FILE = re.compile(
    r"(^|/)(\.env[^/]*|[^/]*\.(ya?ml|toml|ini|cfg|conf|properties|sh|ps1|tf|env)|"
    r"Dockerfile[^/]*|docker-compose[^/]*|compose[^/]*|Makefile|Procfile)$",
    re.I,
)
GENERATED_NAME = re.compile(r"(^|[._/-])(generated|gen)([._/-]|$)", re.I)
GENERATED_HEADER = re.compile(
    r"@generated|do not edit|auto-?generated|code generated by|this file was generated", re.I
)


def tracked(root: Path) -> list[Path]:
    try:
        out = subprocess.run(
            ["git", "-C", str(root), "ls-files", "-z"], capture_output=True, check=True
        ).stdout.decode("utf-8", "replace")
        files = [root / p for p in out.split("\0") if p]
        if files:
            return files
    except (OSError, subprocess.CalledProcessError):
        pass
    return [p for p in root.rglob("*") if p.is_file()]


def wanted(root: Path, path: Path) -> bool:
    rel = path.relative_to(root).parts
    if any(part in SKIP_DIRS for part in rel[:-1]):
        return False
    name = path.name
    if name in SKIP_NAMES or any(name.endswith(s) for s in SKIP_SUFFIXES):
        return False
    try:
        return path.stat().st_size < 2_000_000
    except OSError:
        return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("repo", type=Path)
    ap.add_argument("--known", type=Path, help="unrent scan JSON; drop what its evidence covers")
    ap.add_argument("--all", action="store_true", help="also hosts that do not look like APIs")
    ap.add_argument(
        "--top",
        type=int,
        default=None,
        help="rows per list (default: all with --known, else 60; 0 = all)",
    )
    args = ap.parse_args()
    root = args.repo.resolve()
    if args.top is None:
        args.top = 0 if args.known else 60

    known = ""
    if args.known:
        data = json.loads(args.known.read_text("utf-8"))
        known = json.dumps(
            [data.get(k) for k in ("found", "models_named", "env_template_only", "open_source")]
        ).lower()

    hosts: dict[str, list[str]] = defaultdict(list)
    settings: dict[str, list[str]] = defaultdict(list)
    # A generated catalog (models.dev, an OpenAPI client) can name hundreds of hosts.
    # They are one finding, a long tail of providers, so they get one line per file.
    generated: dict[str, set[str]] = defaultdict(set)
    configured: set[str] = set()  # settings read from the environment or set in config
    for path in tracked(root):
        if not wanted(root, path):
            continue
        try:
            text = path.read_text("utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        rel = path.relative_to(root).as_posix()
        is_generated = bool(GENERATED_NAME.search(path.name) or GENERATED_HEADER.search(text[:600]))
        is_config = bool(CONFIG_FILE.search(rel))
        where_tag = " (test)" if TEST_PART.search(rel) else ""
        notebook = rel.endswith(".ipynb")
        cell, part = "code", "source"
        for n, line in enumerate(text.splitlines(), 1):
            if len(line) > 1000:
                continue
            if notebook:
                # Only the source of code cells is a dependency. Markdown cells and
                # saved outputs (a generated report full of links) are not.
                if m := CELL_TYPE.search(line):
                    cell = m.group(1)
                if m := NB_PART.match(line):
                    part = m.group(1)
                if cell != "code" or part != "source":
                    continue
            for m in URL.finditer(line):
                host = m.group(1).lower()
                if NOISE.search(host) or re.match(r"^\d+\.\d+\.\d+\.\d+$", host):
                    continue
                if not args.all and not API_HINT.search(host + (m.group(2) or "")):
                    continue
                if is_generated:
                    generated[rel].add(host)
                    continue
                hosts[host].append(f"{rel}:{n}{where_tag}")
            for m in SETTING.finditer(line):
                name = m.group(1)
                if not GENERIC_SETTINGS.match(name) and not is_generated:
                    settings[name].append(f"{rel}:{n}{where_tag}")
                    if is_config or ENV_READ.search(line):
                        configured.add(name)

    constants = [k for k in settings if k not in configured]
    settings = {k: v for k, v in settings.items() if k in configured}
    test_only: list[str] = []

    def unexplained(items: dict[str, list[str]], key_of) -> list[tuple[str, list[str]]]:
        rows = []
        for k, v in items.items():
            if known and key_of(k) in known:
                continue
            if all(w.endswith(" (test)") for w in v):
                test_only.append(k)  # a fixture, rarely a dependency: names only
                continue
            rows.append((k, v))
        rows.sort(key=lambda kv: (-len(kv[1]), kv[0]))
        if args.top and len(rows) > args.top:
            # the cut rows are the rare ones, which is where unknown vendors hide
            print(f"({len(rows) - args.top} more rows not shown; --top 0 shows all)")
            return rows[: args.top]
        return rows

    title = "not in unrent's evidence" if known else "all"
    print(f"# API hosts ({title})")
    for host, where in unexplained(hosts, str.lower):
        print(f"{host}  x{len(where)}  {', '.join(where[:3])}")
    print(f"\n# Credential and endpoint settings ({title})")
    for name, where in unexplained(settings, str.lower):
        print(f"{name}  x{len(where)}  {', '.join(where[:3])}")
    if generated:
        print("\n# Generated files (one line each: a long tail of providers, not one service)")
        for rel, names in sorted(generated.items(), key=lambda kv: -len(kv[1])):
            new = sorted(h for h in names if not known or h not in known)
            print(f"{rel}  {len(names)} hosts, {len(new)} not in unrent's evidence: "
                  f"{', '.join(new[:12])}{' ...' if len(new) > 12 else ''}")  # fmt: skip
    if test_only:
        print(f"\n# Only in tests ({len(test_only)}): {', '.join(sorted(test_only))}")
    if constants:
        print(f"\n({len(constants)} *_KEY/*_URL-style names never read from the environment or")
        print(" set in config were left out as code constants)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
